channels:
- pytorch
- conda-forge
- defaults
dependencies:
- python=3.8
- bandit=1.7.2
- flake8=4.0.1
- black=22.10.0
- matplotlib=3.5.1
- pytorch=1.11.0
- seaborn=0.12.1
- tianshou=0.4.5
- torchaudio=0.11.0
- torchmetrics=0.10.0
- torchvision=0.12.0
- python-levenshtein==0.12.2
- transformers==4.24.0
- nltk==3.7
- fuzzywuzzy
- sacrebleu==2.3.1
- wandb
- pip
- pip:
  - einops==0.6.0